[package]
name = "bitty-ipc-devtools"
description = "DevTools protocol for Bitty IPC"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["ipc", "bitty", "devtools"]
categories = ["development-tools"]
publish = true

[lints]
workspace = true

[dependencies]
bitty-ipc-api = { path = "../bitty-ipc-api", version = "0.0.1" }
bitty-ipc-core = { path = "../bitty-ipc-core", version = "0.0.1" }
bitty-ipc-auth = { path = "../bitty-ipc-auth", version = "0.0.1" }
base16ct = { version = "0.3.0", features = ["alloc"] }
getrandom.workspace = true
sha2 = "0.11.0-pre.5"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.135"
